
#Helm setup
- name: Installing Helm
  block:
  - name: Download Helm GPG key
    get_url:
      url: https://baltocdn.com/helm/signing.asc
      dest: /tmp/helm-signing.asc
  - name: Import Helm GPG key
    shell:
      cmd: cat /tmp/helm-signing.asc | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null
  - name: Install transport packages
    apt:
      name: apt-transport-https
      state: present
  - name: Determine architecture
    command: dpkg --print-architecture
    register: architecture
  - name: Configure Helm repository
    blockinfile:
      path: /etc/apt/sources.list.d/helm-stable-debian.list
      block: |
        deb [arch={{ architecture.stdout }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
      create: yes
  - name: Update apt package cache
    apt:
      update_cache: yes
  - name: Install Helm
    apt:
      name: helm
      state: present

- name: Install kubectl
  command: snap install kubectl --classic


#Installing yq

- name: add the PPA repository
  apt_repository:
    repo: ppa:rmescandon/yq
    state: present

- name: update Package Lists
  apt:
    update_cache: yes
