#controller and manager install

- name: Add kubeslice chart repo
  kubernetes.core.helm_repository:
    name: kubeslice
    repo_url: "https://kubeslice.aveshalabs.io/repository/kubeslice-helm-ent-prod/"

- name: update helm repo
  command: helm repo update

#Prometheus install

- name: deploy prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: kubeslice/prometheus
    release_namespace: monitoring
    create_namespace: true
    kubeconfig: /root/.kube/controller_config
